using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "9b2190e9d4acca1a")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IHideControls, ISocialMediaLinks
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Images
		///</summary>
		[ImplementPropertyType("aboutImages")]
		public IEnumerable<IPublishedContent> AboutImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("aboutImages"); }
		}

		///<summary>
		/// About Text
		///</summary>
		[ImplementPropertyType("aboutText")]
		public IHtmlString AboutText
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutText"); }
		}

		///<summary>
		/// About Title
		///</summary>
		[ImplementPropertyType("aboutTitle")]
		public string AboutTitle
		{
			get { return this.GetPropertyValue<string>("aboutTitle"); }
		}

		///<summary>
		/// Contact Email
		///</summary>
		[ImplementPropertyType("contactEmail")]
		public string ContactEmail
		{
			get { return this.GetPropertyValue<string>("contactEmail"); }
		}

		///<summary>
		/// contact Title
		///</summary>
		[ImplementPropertyType("contactTitle")]
		public string ContactTitle
		{
			get { return this.GetPropertyValue<string>("contactTitle"); }
		}

		///<summary>
		/// Home Banner Text
		///</summary>
		[ImplementPropertyType("homeBannerText")]
		public string HomeBannerText
		{
			get { return this.GetPropertyValue<string>("homeBannerText"); }
		}

		///<summary>
		/// Home Landing Image
		///</summary>
		[ImplementPropertyType("homeLandingImage")]
		public IPublishedContent HomeLandingImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("homeLandingImage"); }
		}

		///<summary>
		/// homeSlider
		///</summary>
		[ImplementPropertyType("homeSlider")]
		public IEnumerable<IPublishedContent> HomeSlider
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("homeSlider"); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return Umbraco.Web.PublishedContentModels.SocialMediaLinks.GetEmail(this); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return Umbraco.Web.PublishedContentModels.SocialMediaLinks.GetFacebook(this); }
		}

		///<summary>
		/// phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return Umbraco.Web.PublishedContentModels.SocialMediaLinks.GetPhoneNumber(this); }
		}

		///<summary>
		/// Vimeo
		///</summary>
		[ImplementPropertyType("vimeo")]
		public string Vimeo
		{
			get { return Umbraco.Web.PublishedContentModels.SocialMediaLinks.GetVimeo(this); }
		}
	}

	/// <summary>About Us</summary>
	[PublishedContentModel("aboutUs")]
	public partial class AboutUs : PublishedContentModel, IArtist, IBanner, ICTA, IHideControls, ITextSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// about Text Col 1
		///</summary>
		[ImplementPropertyType("aboutTextCol1")]
		public IHtmlString AboutTextCol1
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutTextCol1"); }
		}

		///<summary>
		/// About Text Col 2
		///</summary>
		[ImplementPropertyType("aboutTextCol2")]
		public IHtmlString AboutTextCol2
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutTextCol2"); }
		}

		///<summary>
		/// subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return this.GetPropertyValue<string>("subtitle"); }
		}

		///<summary>
		/// underBannerImages
		///</summary>
		[ImplementPropertyType("underBannerImages")]
		public IEnumerable<IPublishedContent> UnderBannerImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("underBannerImages"); }
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistBio(this); }
		}

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistImage(this); }
		}

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistName(this); }
		}

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetPortfolioImages(this); }
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerAuthor(this); }
		}

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetWitteBox(this); }
		}

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetZwarteText(this); }
		}

		///<summary>
		/// CTAImage
		///</summary>
		[ImplementPropertyType("ctaImage")]
		public IPublishedContent CtaImage
		{
			get { return Umbraco.Web.PublishedContentModels.CTA.GetCtaImage(this); }
		}

		///<summary>
		/// cta Text
		///</summary>
		[ImplementPropertyType("ctaText")]
		public string CtaText
		{
			get { return Umbraco.Web.PublishedContentModels.CTA.GetCtaText(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("titleText")]
		public string TitleText
		{
			get { return Umbraco.Web.PublishedContentModels.TextSection.GetTitleText(this); }
		}
	}

	/// <summary>Corporate Identities</summary>
	[PublishedContentModel("corporateIdentities")]
	public partial class CorporateIdentities : PublishedContentModel, IArtist, IBanner, IHideControls, ITextSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "corporateIdentities";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CorporateIdentities(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CorporateIdentities, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BlackBox Text
		///</summary>
		[ImplementPropertyType("blackBoxText")]
		public IHtmlString BlackBoxText
		{
			get { return this.GetPropertyValue<IHtmlString>("blackBoxText"); }
		}

		///<summary>
		/// BlackBox Title
		///</summary>
		[ImplementPropertyType("blackBoxTitle")]
		public string BlackBoxTitle
		{
			get { return this.GetPropertyValue<string>("blackBoxTitle"); }
		}

		///<summary>
		/// fotoRechts1
		///</summary>
		[ImplementPropertyType("fotoRechts1")]
		public IPublishedContent FotoRechts1
		{
			get { return this.GetPropertyValue<IPublishedContent>("fotoRechts1"); }
		}

		///<summary>
		/// fotoRechts2
		///</summary>
		[ImplementPropertyType("fotoRechts2")]
		public IPublishedContent FotoRechts2
		{
			get { return this.GetPropertyValue<IPublishedContent>("fotoRechts2"); }
		}

		///<summary>
		/// fotoRechts3
		///</summary>
		[ImplementPropertyType("fotoRechts3")]
		public IPublishedContent FotoRechts3
		{
			get { return this.GetPropertyValue<IPublishedContent>("fotoRechts3"); }
		}

		///<summary>
		/// fotoRechts4
		///</summary>
		[ImplementPropertyType("fotoRechts4")]
		public IPublishedContent FotoRechts4
		{
			get { return this.GetPropertyValue<IPublishedContent>("fotoRechts4"); }
		}

		///<summary>
		/// fotosOnder: foto's onder het zwarte block
		///</summary>
		[ImplementPropertyType("fotosOnder")]
		public IEnumerable<IPublishedContent> FotosOnder
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("fotosOnder"); }
		}

		///<summary>
		/// subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return this.GetPropertyValue<string>("subtitle"); }
		}

		///<summary>
		/// subtitle2
		///</summary>
		[ImplementPropertyType("subtitle2")]
		public string Subtitle2
		{
			get { return this.GetPropertyValue<string>("subtitle2"); }
		}

		///<summary>
		/// subtitle3
		///</summary>
		[ImplementPropertyType("subtitle3")]
		public string Subtitle3
		{
			get { return this.GetPropertyValue<string>("subtitle3"); }
		}

		///<summary>
		/// text
		///</summary>
		[ImplementPropertyType("text")]
		public IHtmlString Text
		{
			get { return this.GetPropertyValue<IHtmlString>("text"); }
		}

		///<summary>
		/// text2
		///</summary>
		[ImplementPropertyType("text2")]
		public IHtmlString Text2
		{
			get { return this.GetPropertyValue<IHtmlString>("text2"); }
		}

		///<summary>
		/// text3
		///</summary>
		[ImplementPropertyType("text3")]
		public IHtmlString Text3
		{
			get { return this.GetPropertyValue<IHtmlString>("text3"); }
		}

		///<summary>
		/// title2
		///</summary>
		[ImplementPropertyType("title2")]
		public string Title2
		{
			get { return this.GetPropertyValue<string>("title2"); }
		}

		///<summary>
		/// title3
		///</summary>
		[ImplementPropertyType("title3")]
		public string Title3
		{
			get { return this.GetPropertyValue<string>("title3"); }
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistBio(this); }
		}

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistImage(this); }
		}

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistName(this); }
		}

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetPortfolioImages(this); }
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerAuthor(this); }
		}

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetWitteBox(this); }
		}

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetZwarteText(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("titleText")]
		public string TitleText
		{
			get { return Umbraco.Web.PublishedContentModels.TextSection.GetTitleText(this); }
		}
	}

	/// <summary>Graphic Design</summary>
	[PublishedContentModel("graphicDesign")]
	public partial class GraphicDesign : PublishedContentModel, IArtist, IBanner, ICTA, IHideControls, ITextSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "graphicDesign";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GraphicDesign(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GraphicDesign, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// adobeCC
		///</summary>
		[ImplementPropertyType("adobeCC")]
		public string AdobeCC
		{
			get { return this.GetPropertyValue<string>("adobeCC"); }
		}

		///<summary>
		/// adobeCCFoto
		///</summary>
		[ImplementPropertyType("adobeCCFoto")]
		public IPublishedContent AdobeCcfoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("adobeCCFoto"); }
		}

		///<summary>
		/// DTP
		///</summary>
		[ImplementPropertyType("dTP")]
		public string DTP
		{
			get { return this.GetPropertyValue<string>("dTP"); }
		}

		///<summary>
		/// dtp Foto
		///</summary>
		[ImplementPropertyType("dtpFoto")]
		public IPublishedContent DtpFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("dtpFoto"); }
		}

		///<summary>
		/// graphicColLinks
		///</summary>
		[ImplementPropertyType("graphicColLinks")]
		public IHtmlString GraphicColLinks
		{
			get { return this.GetPropertyValue<IHtmlString>("graphicColLinks"); }
		}

		///<summary>
		/// graphicColRechts
		///</summary>
		[ImplementPropertyType("graphicColRechts")]
		public IHtmlString GraphicColRechts
		{
			get { return this.GetPropertyValue<IHtmlString>("graphicColRechts"); }
		}

		///<summary>
		/// graphicImages
		///</summary>
		[ImplementPropertyType("graphicImages")]
		public IEnumerable<IPublishedContent> GraphicImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("graphicImages"); }
		}

		///<summary>
		/// ontwerp
		///</summary>
		[ImplementPropertyType("ontwerp")]
		public string Ontwerp
		{
			get { return this.GetPropertyValue<string>("ontwerp"); }
		}

		///<summary>
		/// ontwerp Foto
		///</summary>
		[ImplementPropertyType("ontwerpFoto")]
		public IPublishedContent OntwerpFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("ontwerpFoto"); }
		}

		///<summary>
		/// webdesign
		///</summary>
		[ImplementPropertyType("webdesign")]
		public string Webdesign
		{
			get { return this.GetPropertyValue<string>("webdesign"); }
		}

		///<summary>
		/// webdesignFoto
		///</summary>
		[ImplementPropertyType("webdesignFoto")]
		public IPublishedContent WebdesignFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("webdesignFoto"); }
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistBio(this); }
		}

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistImage(this); }
		}

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistName(this); }
		}

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetPortfolioImages(this); }
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerAuthor(this); }
		}

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetWitteBox(this); }
		}

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetZwarteText(this); }
		}

		///<summary>
		/// CTAImage
		///</summary>
		[ImplementPropertyType("ctaImage")]
		public IPublishedContent CtaImage
		{
			get { return Umbraco.Web.PublishedContentModels.CTA.GetCtaImage(this); }
		}

		///<summary>
		/// cta Text
		///</summary>
		[ImplementPropertyType("ctaText")]
		public string CtaText
		{
			get { return Umbraco.Web.PublishedContentModels.CTA.GetCtaText(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("titleText")]
		public string TitleText
		{
			get { return Umbraco.Web.PublishedContentModels.TextSection.GetTitleText(this); }
		}
	}

	/// <summary>events</summary>
	[PublishedContentModel("events")]
	public partial class Events : PublishedContentModel, IArtist, IBanner, IHideControls, ITextSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "events";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Events(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Events, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// concept Foto
		///</summary>
		[ImplementPropertyType("conceptFoto")]
		public IPublishedContent ConceptFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("conceptFoto"); }
		}

		///<summary>
		/// conceptText
		///</summary>
		[ImplementPropertyType("conceptText")]
		public IHtmlString ConceptText
		{
			get { return this.GetPropertyValue<IHtmlString>("conceptText"); }
		}

		///<summary>
		/// conceptTitle
		///</summary>
		[ImplementPropertyType("conceptTitle")]
		public string ConceptTitle
		{
			get { return this.GetPropertyValue<string>("conceptTitle"); }
		}

		///<summary>
		/// fotosLinks
		///</summary>
		[ImplementPropertyType("fotosLinks")]
		public IEnumerable<IPublishedContent> FotosLinks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("fotosLinks"); }
		}

		///<summary>
		/// fotosRechts
		///</summary>
		[ImplementPropertyType("fotosRechts")]
		public IEnumerable<IPublishedContent> FotosRechts
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("fotosRechts"); }
		}

		///<summary>
		/// logistiek Foto
		///</summary>
		[ImplementPropertyType("logistiekFoto")]
		public IPublishedContent LogistiekFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("logistiekFoto"); }
		}

		///<summary>
		/// logistiekText
		///</summary>
		[ImplementPropertyType("logistiekText")]
		public IHtmlString LogistiekText
		{
			get { return this.GetPropertyValue<IHtmlString>("logistiekText"); }
		}

		///<summary>
		/// logistiekTitle
		///</summary>
		[ImplementPropertyType("logistiekTitle")]
		public string LogistiekTitle
		{
			get { return this.GetPropertyValue<string>("logistiekTitle"); }
		}

		///<summary>
		/// Pers Foto
		///</summary>
		[ImplementPropertyType("persFoto")]
		public IPublishedContent PersFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("persFoto"); }
		}

		///<summary>
		/// PersText
		///</summary>
		[ImplementPropertyType("persText")]
		public IHtmlString PersText
		{
			get { return this.GetPropertyValue<IHtmlString>("persText"); }
		}

		///<summary>
		/// PersTitle
		///</summary>
		[ImplementPropertyType("persTitle")]
		public string PersTitle
		{
			get { return this.GetPropertyValue<string>("persTitle"); }
		}

		///<summary>
		/// Quote1
		///</summary>
		[ImplementPropertyType("quote")]
		public IHtmlString Quote
		{
			get { return this.GetPropertyValue<IHtmlString>("quote"); }
		}

		///<summary>
		/// quote2
		///</summary>
		[ImplementPropertyType("quote2")]
		public IHtmlString Quote2
		{
			get { return this.GetPropertyValue<IHtmlString>("quote2"); }
		}

		///<summary>
		/// quote2 Author
		///</summary>
		[ImplementPropertyType("quote2Author")]
		public string Quote2Author
		{
			get { return this.GetPropertyValue<string>("quote2Author"); }
		}

		///<summary>
		/// quote 3
		///</summary>
		[ImplementPropertyType("quote3")]
		public IHtmlString Quote3
		{
			get { return this.GetPropertyValue<IHtmlString>("quote3"); }
		}

		///<summary>
		/// quote3 Author
		///</summary>
		[ImplementPropertyType("quote3Author")]
		public string Quote3Author
		{
			get { return this.GetPropertyValue<string>("quote3Author"); }
		}

		///<summary>
		/// quote Author1
		///</summary>
		[ImplementPropertyType("quoteAuthor")]
		public string QuoteAuthor
		{
			get { return this.GetPropertyValue<string>("quoteAuthor"); }
		}

		///<summary>
		/// subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public IHtmlString Subtitle
		{
			get { return this.GetPropertyValue<IHtmlString>("subtitle"); }
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistBio(this); }
		}

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistImage(this); }
		}

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistName(this); }
		}

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetPortfolioImages(this); }
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerAuthor(this); }
		}

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetWitteBox(this); }
		}

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetZwarteText(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("titleText")]
		public string TitleText
		{
			get { return Umbraco.Web.PublishedContentModels.TextSection.GetTitleText(this); }
		}
	}

	/// <summary>portfolio</summary>
	[PublishedContentModel("portfolio")]
	public partial class Portfolio : PublishedContentModel, IArtist, IBanner, IHideControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "portfolio";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Portfolio(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Portfolio, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistBio(this); }
		}

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistImage(this); }
		}

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistName(this); }
		}

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetPortfolioImages(this); }
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerAuthor(this); }
		}

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetWitteBox(this); }
		}

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetZwarteText(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}
	}

	// Mixin content Type 1069 with alias "banner"
	/// <summary>Banner</summary>
	public partial interface IBanner : IPublishedContent
	{
		/// <summary>Banner Author</summary>
		string BannerAuthor { get; }

		/// <summary>Banner Foto</summary>
		IPublishedContent BannerImage { get; }

		/// <summary>witte balk</summary>
		string WitteBox { get; }

		/// <summary>zwarte Balk</summary>
		string ZwarteText { get; }
	}

	/// <summary>Banner</summary>
	[PublishedContentModel("banner")]
	public partial class Banner : PublishedContentModel, IBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "banner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Banner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Banner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return GetBannerAuthor(this); }
		}

		/// <summary>Static getter for Banner Author</summary>
		public static string GetBannerAuthor(IBanner that) { return that.GetPropertyValue<string>("bannerAuthor"); }

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return GetBannerImage(this); }
		}

		/// <summary>Static getter for Banner Foto</summary>
		public static IPublishedContent GetBannerImage(IBanner that) { return that.GetPropertyValue<IPublishedContent>("bannerImage"); }

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return GetWitteBox(this); }
		}

		/// <summary>Static getter for witte balk</summary>
		public static string GetWitteBox(IBanner that) { return that.GetPropertyValue<string>("witteBox"); }

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return GetZwarteText(this); }
		}

		/// <summary>Static getter for zwarte Balk</summary>
		public static string GetZwarteText(IBanner that) { return that.GetPropertyValue<string>("zwarteText"); }
	}

	// Mixin content Type 1073 with alias "artist"
	/// <summary>Artist</summary>
	public partial interface IArtist : IPublishedContent
	{
		/// <summary>Artist Bio</summary>
		IHtmlString ArtistBio { get; }

		/// <summary>Artist Image</summary>
		IPublishedContent ArtistImage { get; }

		/// <summary>Artist Name</summary>
		string ArtistName { get; }

		/// <summary>portfolio Images</summary>
		IEnumerable<IPublishedContent> PortfolioImages { get; }
	}

	/// <summary>Artist</summary>
	[PublishedContentModel("artist")]
	public partial class Artist : PublishedContentModel, IArtist
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "artist";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Artist(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Artist, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return GetArtistBio(this); }
		}

		/// <summary>Static getter for Artist Bio</summary>
		public static IHtmlString GetArtistBio(IArtist that) { return that.GetPropertyValue<IHtmlString>("artistBio"); }

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return GetArtistImage(this); }
		}

		/// <summary>Static getter for Artist Image</summary>
		public static IPublishedContent GetArtistImage(IArtist that) { return that.GetPropertyValue<IPublishedContent>("artistImage"); }

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return GetArtistName(this); }
		}

		/// <summary>Static getter for Artist Name</summary>
		public static string GetArtistName(IArtist that) { return that.GetPropertyValue<string>("artistName"); }

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return GetPortfolioImages(this); }
		}

		/// <summary>Static getter for portfolio Images</summary>
		public static IEnumerable<IPublishedContent> GetPortfolioImages(IArtist that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("portfolioImages"); }
	}

	// Mixin content Type 1077 with alias "cTA"
	/// <summary>CTA</summary>
	public partial interface ICTA : IPublishedContent
	{
		/// <summary>CTAImage</summary>
		IPublishedContent CtaImage { get; }

		/// <summary>cta Text</summary>
		string CtaText { get; }
	}

	/// <summary>CTA</summary>
	[PublishedContentModel("cTA")]
	public partial class CTA : PublishedContentModel, ICTA
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cTA";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CTA(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CTA, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// CTAImage
		///</summary>
		[ImplementPropertyType("ctaImage")]
		public IPublishedContent CtaImage
		{
			get { return GetCtaImage(this); }
		}

		/// <summary>Static getter for CTAImage</summary>
		public static IPublishedContent GetCtaImage(ICTA that) { return that.GetPropertyValue<IPublishedContent>("ctaImage"); }

		///<summary>
		/// cta Text
		///</summary>
		[ImplementPropertyType("ctaText")]
		public string CtaText
		{
			get { return GetCtaText(this); }
		}

		/// <summary>Static getter for cta Text</summary>
		public static string GetCtaText(ICTA that) { return that.GetPropertyValue<string>("ctaText"); }
	}

	// Mixin content Type 1079 with alias "textSection"
	/// <summary>text section</summary>
	public partial interface ITextSection : IPublishedContent
	{
		/// <summary>Title</summary>
		string TitleText { get; }
	}

	/// <summary>text section</summary>
	[PublishedContentModel("textSection")]
	public partial class TextSection : PublishedContentModel, ITextSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "textSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TextSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TextSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("titleText")]
		public string TitleText
		{
			get { return GetTitleText(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitleText(ITextSection that) { return that.GetPropertyValue<string>("titleText"); }
	}

	/// <summary>Film Video</summary>
	[PublishedContentModel("filmVideo")]
	public partial class FilmVideo : PublishedContentModel, IArtist, IBanner, ICTA, IHideControls, ITextSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "filmVideo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FilmVideo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FilmVideo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// film text col 1
		///</summary>
		[ImplementPropertyType("filmTextCol1")]
		public IHtmlString FilmTextCol1
		{
			get { return this.GetPropertyValue<IHtmlString>("filmTextCol1"); }
		}

		///<summary>
		/// film text col 2
		///</summary>
		[ImplementPropertyType("filmTextCol2")]
		public IHtmlString FilmTextCol2
		{
			get { return this.GetPropertyValue<IHtmlString>("filmTextCol2"); }
		}

		///<summary>
		/// subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return this.GetPropertyValue<string>("subtitle"); }
		}

		///<summary>
		/// Artist Bio
		///</summary>
		[ImplementPropertyType("artistBio")]
		public IHtmlString ArtistBio
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistBio(this); }
		}

		///<summary>
		/// Artist Image
		///</summary>
		[ImplementPropertyType("artistImage")]
		public IPublishedContent ArtistImage
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistImage(this); }
		}

		///<summary>
		/// Artist Name
		///</summary>
		[ImplementPropertyType("artistName")]
		public string ArtistName
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetArtistName(this); }
		}

		///<summary>
		/// portfolio Images
		///</summary>
		[ImplementPropertyType("portfolioImages")]
		public IEnumerable<IPublishedContent> PortfolioImages
		{
			get { return Umbraco.Web.PublishedContentModels.Artist.GetPortfolioImages(this); }
		}

		///<summary>
		/// Banner Author
		///</summary>
		[ImplementPropertyType("bannerAuthor")]
		public string BannerAuthor
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerAuthor(this); }
		}

		///<summary>
		/// Banner Foto
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}

		///<summary>
		/// witte balk
		///</summary>
		[ImplementPropertyType("witteBox")]
		public string WitteBox
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetWitteBox(this); }
		}

		///<summary>
		/// zwarte Balk
		///</summary>
		[ImplementPropertyType("zwarteText")]
		public string ZwarteText
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetZwarteText(this); }
		}

		///<summary>
		/// CTAImage
		///</summary>
		[ImplementPropertyType("ctaImage")]
		public IPublishedContent CtaImage
		{
			get { return Umbraco.Web.PublishedContentModels.CTA.GetCtaImage(this); }
		}

		///<summary>
		/// cta Text
		///</summary>
		[ImplementPropertyType("ctaText")]
		public string CtaText
		{
			get { return Umbraco.Web.PublishedContentModels.CTA.GetCtaText(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("titleText")]
		public string TitleText
		{
			get { return Umbraco.Web.PublishedContentModels.TextSection.GetTitleText(this); }
		}
	}

	// Mixin content Type 1125 with alias "hideControls"
	/// <summary>Hide Controls</summary>
	public partial interface IHideControls : IPublishedContent
	{
		/// <summary>Umbraco Navi Hide</summary>
		bool UmbracoNaviHide { get; }
	}

	/// <summary>Hide Controls</summary>
	[PublishedContentModel("hideControls")]
	public partial class HideControls : PublishedContentModel, IHideControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hideControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HideControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HideControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Umbraco Navi Hide: pagina onzichtbaar maken
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Umbraco Navi Hide</summary>
		public static bool GetUmbracoNaviHide(IHideControls that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }
	}

	// Mixin content Type 1126 with alias "socialMediaLinks"
	/// <summary>Social media links</summary>
	public partial interface ISocialMediaLinks : IPublishedContent
	{
		/// <summary>email</summary>
		string Email { get; }

		/// <summary>Facebook</summary>
		string Facebook { get; }

		/// <summary>phone Number</summary>
		string PhoneNumber { get; }

		/// <summary>Vimeo</summary>
		string Vimeo { get; }
	}

	/// <summary>Social media links</summary>
	[PublishedContentModel("socialMediaLinks")]
	public partial class SocialMediaLinks : PublishedContentModel, ISocialMediaLinks
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "socialMediaLinks";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialMediaLinks(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialMediaLinks, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return GetEmail(this); }
		}

		/// <summary>Static getter for email</summary>
		public static string GetEmail(ISocialMediaLinks that) { return that.GetPropertyValue<string>("email"); }

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return GetFacebook(this); }
		}

		/// <summary>Static getter for Facebook</summary>
		public static string GetFacebook(ISocialMediaLinks that) { return that.GetPropertyValue<string>("facebook"); }

		///<summary>
		/// phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return GetPhoneNumber(this); }
		}

		/// <summary>Static getter for phone Number</summary>
		public static string GetPhoneNumber(ISocialMediaLinks that) { return that.GetPropertyValue<string>("phoneNumber"); }

		///<summary>
		/// Vimeo
		///</summary>
		[ImplementPropertyType("vimeo")]
		public string Vimeo
		{
			get { return GetVimeo(this); }
		}

		/// <summary>Static getter for Vimeo</summary>
		public static string GetVimeo(ISocialMediaLinks that) { return that.GetPropertyValue<string>("vimeo"); }
	}

	/// <summary>video item</summary>
	[PublishedContentModel("videoItem")]
	public partial class VideoItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "videoItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VideoItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VideoItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// embed URL
		///</summary>
		[ImplementPropertyType("embedURL")]
		public Newtonsoft.Json.Linq.JToken EmbedUrl
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("embedURL"); }
		}
	}

	/// <summary>About Item</summary>
	[PublishedContentModel("aboutItem")]
	public partial class AboutItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// Google
		///</summary>
		[ImplementPropertyType("google")]
		public string Google
		{
			get { return this.GetPropertyValue<string>("google"); }
		}

		///<summary>
		/// LinkedIn
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// Member Bio
		///</summary>
		[ImplementPropertyType("memberBio")]
		public IHtmlString MemberBio
		{
			get { return this.GetPropertyValue<IHtmlString>("memberBio"); }
		}

		///<summary>
		/// Member Functie
		///</summary>
		[ImplementPropertyType("memberFunctie")]
		public string MemberFunctie
		{
			get { return this.GetPropertyValue<string>("memberFunctie"); }
		}

		///<summary>
		/// MemberName: naam van de member
		///</summary>
		[ImplementPropertyType("memberName")]
		public string MemberName
		{
			get { return this.GetPropertyValue<string>("memberName"); }
		}

		///<summary>
		/// Member Picture
		///</summary>
		[ImplementPropertyType("memberPicture")]
		public IPublishedContent MemberPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("memberPicture"); }
		}

		///<summary>
		/// twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
